import { IMAGE_MODELS, imageCapabilityProblem, imageModelCapability } from '@adelaide-sphere/database/automation';
import type {
  SettingDeclaration,
  SettingGroupDeclaration,
} from './registry.js';
const declaration = (
  key: string,
  label: string,
  type: SettingDeclaration['type'],
  value: boolean | number | string,
  bounds: SettingDeclaration['bounds'],
  description: string,
): SettingDeclaration => ({
  key,
  label,
  type,
  default: value,
  bounds,
  description,
  visibility: 'private',
  effect: 'runtime',
  sensitive: false,
  viewPermission: 'ai_content.configure',
  updatePermission: 'ai_content.configure',
  invalidates: [],
  enforcedBy:
    'packages/database/src/automation (research, generation requests, budget reservations and settlement read these values in their transactions)',
  consequence:
    'While enabled: free public research, budgeted drafts from verified research, and featured images generated only when a person asks. Everything needs human approval; no cadence or auto-publishing.',
});
/** The saved aspect ratio, resolution and quality must be one request the chosen model supports. */
function imageRequestProblem(values: Record<string, unknown>): Record<string, string> {
  const [provider, model] = [String(values.imageProvider ?? 'openai'), String(values.imageModel ?? '')];
  const cap = imageModelCapability(provider, model);
  if (!cap) return {};
  const problem = imageCapabilityProblem(provider, model, String(values.imageAspectRatio), String(values.imageResolution), String(values.imageQuality), 0);
  if (problem === 'unsupported_quality') return { imageQuality: `${cap.label} supports ${cap.qualities.join(', ')}` };
  if (problem === 'unsupported_resolution') return { imageResolution: `${cap.label} supports ${cap.resolutions.join(', ')}` };
  if (problem) return { imageAspectRatio: `${cap.label} does not support ${String(values.imageAspectRatio)} at ${String(values.imageResolution)}` };
  return {};
}

export const AI_CONTENT_SETTINGS: SettingGroupDeclaration = {
  key: 'ai_content',
  label: 'AI Content',
  description:
    'Topics, free public research, fact review and budgeted, human-approved drafts.',
  owner: 'AiContentModule',
  storeKey: 'defaults',
  viewPermission: 'ai_content.configure',
  updatePermission: 'ai_content.configure',
  validate: (values): Record<string, string> => ({
    ...(values.timezone === 'Australia/Adelaide' ? {} : { timezone: 'This deployment uses Australia/Adelaide' }),
    // Owner decision (Phase 1E): paid images only through an explicit Generate image action.
    ...(values.imageMode === 'automatic' ? { imageMode: 'Automatic image generation is not approved. Use hybrid or manual.' } : {}),
    // Only a listed model of the chosen provider (provider amendment 01, P1); never free text.
    ...(values.imageModel === undefined || imageModelCapability(String(values.imageProvider ?? 'openai'), String(values.imageModel))
      ? {}
      : { imageModel: `Choose a listed model for ${String(values.imageProvider ?? 'openai')}: ${IMAGE_MODELS.filter((m) => m.provider === (values.imageProvider ?? 'openai')).map((m) => m.model).join(', ') || 'none listed yet'}` }),
    ...imageRequestProblem(values),
    // Owner decision (Phase 1G): hardening only; every AI article needs a person's fact confirmation and approval.
    ...(values.publicationMode === 'auto_publish' ? { publicationMode: 'Auto-publishing is not approved: every AI article needs a person to confirm its facts and approve it.' } : {}),
    ...(values.slotTime === undefined || /^([01]\d|2[0-3]):[0-5]\d$/.test(String(values.slotTime)) ? {} : { slotTime: 'Use HH:MM, for example 07:00' }),
    ...(values.slotWeekdays === undefined ||
    (String(values.slotWeekdays).split(',').length > 0 && String(values.slotWeekdays).split(',').every((d) => ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'].includes(d.trim().toLowerCase())))
      ? {}
      : { slotWeekdays: 'Use mon, tue, wed, thu, fri, sat, sun separated by commas' }),
  }),
  note: 'Phase 1F: an optional daily slot starts free research for the next topic a person approved for it. Generation, images and publishing always need a person; auto-publishing stays off.',
  settings: [
    declaration(
      'enabled',
      'AI automation enabled',
      'boolean',
      false,
      {},
      'Master switch. While off, nothing AI starts and scheduled AI articles are held. While on, only the modes below apply.',
    ),
    declaration(
      'titleMode',
      'Topic/title mode',
      'enum',
      'manual',
      { values: ['manual', 'automatic', 'hybrid'] },
      'Automatic or hybrid allows discovery runs to propose topics from configured feeds; every proposal still needs approval.',
    ),
    declaration(
      'publicationMode',
      'Publication mode',
      'enum',
      'review_required',
      { values: ['review_required', 'auto_publish'] },
      'Review required: a person confirms the facts and approves every AI article. Auto-publishing is not approved.',
    ),
    declaration(
      'imageMode',
      'Image mode',
      'enum',
      'hybrid',
      { values: ['manual', 'hybrid', 'automatic'] },
      'Manual: prompt only. Hybrid: prompt only, plus a Generate image action per article. Automatic is not approved.',
    ),
    declaration(
      'location',
      'Configured location',
      'string',
      'Adelaide, South Australia',
      { min: 1, max: 180 },
      'Where the site is about. Its words are ignored when comparing topics, since every topic shares them.',
    ),
    declaration(
      'editorialStrategy',
      'Niche and editorial strategy',
      'string',
      'Useful local discovery, city guides, food, cafes, local businesses and services, lifestyle, and reliably sourced events.',
      { min: 1, max: 2000 },
      'Describe the intended audience, niche and editorial focus. Do not enter secrets or private customer information.',
    ),
    declaration(
      'postingEnabled',
      'Daily slot enabled',
      'boolean',
      false,
      {},
      'While on (and automation is on), each daily slot takes the next topic a person approved for the schedule and starts its free research. It never generates, pays or publishes.',
    ),
    declaration(
      'targetPostsPerDay',
      'Slots per day',
      'integer',
      1,
      { min: 1, max: 1 },
      'One slot a day (owner decision). Publication still needs a person.',
    ),
    declaration(
      'slotTime',
      'Daily slot time (local)',
      'string',
      '07:00',
      { min: 5, max: 5 },
      'HH:MM in the site timezone, daylight saving included.',
    ),
    declaration(
      'slotWeekdays',
      'Slot weekdays',
      'string',
      'mon,tue,wed,thu,fri,sat,sun',
      { min: 3, max: 27 },
      'Comma-separated: mon, tue, wed, thu, fri, sat, sun.',
    ),
    declaration(
      'maxSlotsPerMonth',
      'Slots per month (maximum)',
      'integer',
      30,
      { min: 0, max: 31 },
      'A ceiling, not a target. Zero fills no slots.',
    ),
    declaration(
      'slotGraceMinutes',
      'Slot grace period (minutes)',
      'integer',
      60,
      { min: 5, max: 360 },
      'A slot not started within this long after its time is recorded as missed for review, never caught up.',
    ),
    declaration(
      'timezone',
      'Timezone',
      'string',
      'Australia/Adelaide',
      { min: 1, max: 64 },
      'This deployment uses Australia/Adelaide, including daylight saving.',
    ),
    declaration(
      'budgetEnabled',
      'Budget controls enabled',
      'boolean',
      true,
      {},
      'Each paid call first reserves its worst case against the limits below. While off, no paid call is approved.',
    ),
    declaration(
      'budgetCurrency',
      'Budget currency',
      'enum',
      'USD',
      { values: ['AUD', 'USD', 'EUR', 'GBP'] },
      'Limits and prices use this currency; a price in another is refused. Nothing is converted.',
    ),
    declaration(
      'warningThreshold',
      'Budget warning threshold (%)',
      'integer',
      70,
      { min: 1, max: 100 },
      'Warn, and record it, when spend plus reservations reach this share of a limit.',
    ),
    declaration(
      'hardMonthlyLimitMinor',
      'Hard monthly limit (minor currency units)',
      'integer',
      1000,
      { min: 0, max: 100000000 },
      'Cents: 1000 = 10.00. Every paid call reserves its maximum against this first; zero allows none.',
    ),
    declaration(
      'hardDailyLimitMinor',
      'Hard daily limit (minor currency units)',
      'integer',
      50,
      { min: 0, max: 100000000 },
      'Cents: 50 = 0.50, per day in the configured timezone. Zero allows no paid call.',
    ),
    declaration(
      'maxWorkflowCostMinor',
      'Maximum AI cost per article (minor units)',
      'integer',
      25,
      { min: 0, max: 100000000 },
      'Cumulative per article: every generation, regeneration and suggestion for the same article counts what it holds or spent. A call whose worst case would take the article over this is refused before it is made.',
    ),
    declaration(
      'generationOutputTokenLimit',
      'Maximum output tokens per draft',
      'integer',
      8000,
      { min: 1000, max: 16000 },
      'Caps each draft, reasoning included, and so its worst-case cost.',
    ),
    declaration(
      'maxInternalLinks',
      'Internal links per draft',
      'integer',
      3,
      { min: 0, max: 5 },
      'Links go only to related published articles, each once.',
    ),
    declaration(
      'articleAuthorId',
      'Author of AI-assisted articles',
      'string',
      '',
      { min: 0, max: 64 },
      'An existing active author. Generation stays blocked until one is chosen.',
    ),
    declaration(
      'disclosureText',
      'Reader disclosure',
      'string',
      'AI-assisted content: This article was prepared with AI assistance and reviewed against source information before publication.',
      { min: 1, max: 500 },
      'Shown on published AI-assisted articles; each draft records the wording it used.',
    ),
    declaration(
      'featuredImageRequired',
      'Featured image required to publish',
      'boolean',
      true,
      {},
      'A ready featured image with alt text is needed before an AI article publishes. It can be uploaded or chosen from the library.',
    ),
    declaration(
      'imageProvider',
      'Image provider',
      'enum',
      'openai',
      { values: ['openai', 'xai', 'google'] },
      'Only providers with a listed model, an approved price and a server key can generate.',
    ),
    declaration(
      'imageModel',
      'Image model',
      'string',
      'gpt-image-2.5-flare',
      { min: 1, max: 64 },
      'One of the provider\'s listed models. It changes only by choosing another listed model.',
    ),
    declaration(
      'imageAspectRatio',
      'Generated image aspect ratio',
      'enum',
      '3:2',
      { values: ['3:2', '16:9', '1:1', '2:3'] },
      'Landscape suits a featured image. The model must support it.',
    ),
    declaration(
      'imageResolution',
      'Generated image resolution',
      'enum',
      '1k',
      { values: ['1k', '2k'] },
      'The approved price must cover this resolution.',
    ),
    declaration(
      'imageQuality',
      'Generated image quality',
      'enum',
      'medium',
      { values: ['low', 'medium', 'high', 'auto'] },
      'Higher quality costs more. The model must support it and the approved price must cover it.',
    ),
    declaration(
      'imageDailyLimitMinor',
      'Image budget per day (minor units)',
      'integer',
      0,
      { min: 0, max: 100000000 },
      'Separate from the text budget. Zero allows no image generation.',
    ),
    declaration(
      'imageMonthlyLimitMinor',
      'Image budget per month (minor units)',
      'integer',
      0,
      { min: 0, max: 100000000 },
      'Separate from the text budget. Zero allows no image generation.',
    ),
    declaration(
      'imageDisclosureText',
      'AI image disclosure',
      'string',
      'Illustrative image created with AI.',
      { min: 1, max: 255 },
      'Shown under an AI-generated featured image; each image records the wording it used.',
    ),
    declaration(
      'aiRetentionDays',
      'Keep private AI working data (days)',
      'integer',
      180,
      { min: 30, max: 3650 },
      'After a topic is published, rejected or cancelled. Request payloads, page text, draft output and image prompts are then removed; costs, approvals, claims and audit stay.',
    ),
    declaration(
      'discoveryKeywords',
      'Niche terms for discovery',
      'string',
      'cafe, restaurant, food, market, festival, event, exhibition, museum, gallery, park, beach, trail, walk, winery, bar, shop, opening, guide, family, local business, service',
      { min: 0, max: 1000 },
      'Comma-separated. A feed item must mention one of these to become a topic idea. Empty means discovery proposes nothing.',
    ),
    declaration(
      'excludedKeywords',
      'Excluded terms for discovery',
      'string',
      'celebrity, crime, court, politics, election, lottery, gossip',
      { min: 0, max: 1000 },
      'Comma-separated. Feed items mentioning any of these are never proposed.',
    ),
    declaration(
      'contextPostLimit',
      'Related articles kept as context',
      'integer',
      5,
      { min: 1, max: 10 },
      'How many related published articles a research packet keeps. Drafts are never included.',
    ),
    declaration(
      'freshnessVolatileHours',
      'Freshness: hours, prices, availability, events (hours)',
      'integer',
      24,
      { min: 1, max: 24 },
      'Evidence older than this is stale. The approved ceiling is 24 hours; it can only be shortened.',
    ),
    declaration(
      'freshnessIdentityDays',
      'Freshness: business identity and contact (days)',
      'integer',
      7,
      { min: 1, max: 7 },
      'The approved ceiling is 7 days; it can only be shortened.',
    ),
    declaration(
      'freshnessStableDays',
      'Freshness: stable background (days)',
      'integer',
      30,
      { min: 1, max: 30 },
      'The approved ceiling is 30 days; it can only be shortened.',
    ),
  ],
};
