import type {
  SettingDeclaration,
  SettingGroupDeclaration,
} from './registry.js';
const declaration = (
  key: string,
  label: string,
  type: SettingDeclaration['type'],
  value: boolean | number | string,
  bounds: SettingDeclaration['bounds'],
  description: string,
): SettingDeclaration => ({
  key,
  label,
  type,
  default: value,
  bounds,
  description,
  visibility: 'private',
  effect: 'runtime',
  sensitive: false,
  viewPermission: 'ai_content.configure',
  updatePermission: 'ai_content.configure',
  invalidates: [],
  enforcedBy:
    'packages/database/src/automation (research admission, evaluation and discovery read these values in their transactions)',
  consequence:
    'Research and discovery read only free public sources and run only while automation is enabled. Generation, images, scheduling and auto-publishing are not available in this release.',
});
export const AI_CONTENT_SETTINGS: SettingGroupDeclaration = {
  key: 'ai_content',
  label: 'AI Content',
  description:
    'Topic administration, free public research and fact review. No article generation.',
  owner: 'AiContentModule',
  storeKey: 'defaults',
  viewPermission: 'ai_content.configure',
  updatePermission: 'ai_content.configure',
  validate: (values): Record<string, string> =>
    values.timezone === 'Australia/Adelaide'
      ? {}
      : { timezone: 'This deployment uses Australia/Adelaide' },
  note: 'Phase 1C: when enabled, approved topics are researched from free public sources and discovery reads configured feeds. Nothing is generated or published automatically.',
  settings: [
    declaration(
      'enabled',
      'Automation configured enabled',
      'boolean',
      false,
      {},
      'While off, no research, discovery or other external request starts, and scheduled AI articles are held.',
    ),
    declaration(
      'titleMode',
      'Topic/title mode',
      'enum',
      'manual',
      { values: ['manual', 'automatic', 'hybrid'] },
      'Automatic or hybrid allows discovery runs to propose topics from configured feeds; every proposal still needs approval.',
    ),
    declaration(
      'publicationMode',
      'Publication mode',
      'enum',
      'review_required',
      { values: ['review_required', 'auto_publish'] },
      'Configuration only; no articles are created or published.',
    ),
    declaration(
      'imageMode',
      'Image mode',
      'enum',
      'manual',
      { values: ['manual', 'hybrid', 'automatic'] },
      'Configuration only; no image providers are called.',
    ),
    declaration(
      'location',
      'Configured location',
      'string',
      'Adelaide, South Australia',
      { min: 1, max: 180 },
      'Where the site is about. Its words are ignored when comparing topics, since every topic shares them.',
    ),
    declaration(
      'editorialStrategy',
      'Niche and editorial strategy',
      'string',
      'Useful local discovery, city guides, food, cafes, local businesses and services, lifestyle, and reliably sourced events.',
      { min: 1, max: 2000 },
      'Describe the intended audience, niche and editorial focus. Do not enter secrets or private customer information.',
    ),
    declaration(
      'postingEnabled',
      'Posting configured enabled',
      'boolean',
      false,
      {},
      'No scheduler or publishing automation is active.',
    ),
    declaration(
      'targetPostsPerDay',
      'Target posts per day',
      'integer',
      1,
      { min: 1, max: 24 },
      'Future editorial target, not an active publishing schedule.',
    ),
    declaration(
      'timezone',
      'Timezone',
      'string',
      'Australia/Adelaide',
      { min: 1, max: 64 },
      'This deployment uses Australia/Adelaide, including daylight saving.',
    ),
    declaration(
      'budgetEnabled',
      'Budget controls configured enabled',
      'boolean',
      true,
      {},
      'No spending occurs in this release. Future execution must implement budget enforcement first.',
    ),
    declaration(
      'budgetCurrency',
      'Budget currency',
      'enum',
      'AUD',
      { values: ['AUD', 'USD', 'EUR', 'GBP'] },
      'Currency of the intended limit; no currency conversion or billing is performed.',
    ),
    declaration(
      'warningThreshold',
      'Budget warning threshold (%)',
      'integer',
      80,
      { min: 1, max: 100 },
      'Configured percentage for future budget warnings; no usage statistics exist yet.',
    ),
    declaration(
      'hardMonthlyLimitMinor',
      'Hard monthly limit (minor currency units)',
      'integer',
      0,
      { min: 0, max: 100000000 },
      'Integer cents/pence: 100 = 1.00 in the selected currency. Zero means no paid budget approved. Not an active ledger.',
    ),
    declaration(
      'discoveryKeywords',
      'Niche terms for discovery',
      'string',
      'cafe, restaurant, food, market, festival, event, exhibition, museum, gallery, park, beach, trail, walk, winery, bar, shop, opening, guide, family, local business, service',
      { min: 0, max: 1000 },
      'Comma-separated. A feed item must mention one of these to become a topic idea. Empty means discovery proposes nothing.',
    ),
    declaration(
      'excludedKeywords',
      'Excluded terms for discovery',
      'string',
      'celebrity, crime, court, politics, election, lottery, gossip',
      { min: 0, max: 1000 },
      'Comma-separated. Feed items mentioning any of these are never proposed.',
    ),
    declaration(
      'contextPostLimit',
      'Related articles kept as context',
      'integer',
      5,
      { min: 1, max: 10 },
      'How many related published articles a research packet keeps. Drafts are never included.',
    ),
    declaration(
      'freshnessVolatileHours',
      'Freshness: hours, prices, availability, events (hours)',
      'integer',
      24,
      { min: 1, max: 24 },
      'Evidence older than this is stale. The approved ceiling is 24 hours; it can only be shortened.',
    ),
    declaration(
      'freshnessIdentityDays',
      'Freshness: business identity and contact (days)',
      'integer',
      7,
      { min: 1, max: 7 },
      'The approved ceiling is 7 days; it can only be shortened.',
    ),
    declaration(
      'freshnessStableDays',
      'Freshness: stable background (days)',
      'integer',
      30,
      { min: 1, max: 30 },
      'The approved ceiling is 30 days; it can only be shortened.',
    ),
  ],
};
